version: '3.1'

services:

  db:
    image: postgres
    restart: always
    hostname: db
    build:
      context: .
      dockerfile: DockerFiles/DockerFile-PostgresSQL
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    labels:
      name: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8070:80
    networks:
      - app-network
    environment:
      PGADMIN_DEFAULT_EMAIL: jeffersonlupinacci@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    labels:
      name: pgadmin
      
networks:
  app-network:
    external: true

volumes:
  config-repo:
    external: true