version: '2'
services:

  mongo:
    image: mongo:3
    mem_limit: 128m
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - app-network

  graylog:
    image: graylog/graylog:2.5.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_MESSAGE_JOURNAL_ENABLED=false
      - "GRAYLOG_SERVER_JAVA_OPTS=-Xmx4G"
    mem_limit: 1g
    links:
      - mongo
      - elasticsearch
    expose:
      - 12201/udp
    ports:
      - 9000:9000
      - 12201:12201/udp
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin
    restart: always
    hostname: zipkin
    ports:
      - 9411:9411
    networks:
      - app-network
    labels:
      name: zipkin

networks:
  app-network:
    external: true