FROM alpine:edge

LABEL maintainer="jeffersonlupinacci@gmail.com"

USER root
RUN apk update

# ================
# OpenJdk 8
# ================
RUN apk fetch openjdk8
RUN apk add openjdk8
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk

# ================
# Service Folder
# ================
RUN mkdir -p /opt/lib/target && mkdir -p /opt/logs/ 

# ================
# Remove Fetched 
# ================
RUN rm *.apk